version: "3"
services:
  postgres:
    image: postgres
    restart: always
    volumes:
      - "db-data:/var/lib/postgressql/data"
    networks:
      - topnet
    environment:
#      POSTGRES_PASSWORD: secret
#      POSTGRES_USER: postgres
  backend:
    image: tomcat
    restart: always
    ports:
      - 8080:8080
    volumes:
      - "backend-data:/var/backend"
    networks:
      - topnet
    depends_on:
      - postgres
  frontend:
    image: node:12
    ports:
      - 5000:5000
    volumes:
      - "frontend-data:/var/frontend"
    networks:
      - topnet
networks:
  topnet:
volumes:
  db-data:
  backend-data:./backend
  frontend-data:./frontend