spring.application.name: discovery
server: 
  port: 8082
  servlet.context-path: /

eureka:
  instance.hostname: ${springboot.app.name:discovery}
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl.defaultZone: http://${registry.host:localhost}:${server.port}/eureka/

logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF