spring.application.name: resource
server: 
  port: 8080
  servlet: 
    context-path: /
eureka:
  client:
    serviceUrl.defaultZone: http://${registry.host:localhost}:${registry.port:8082}/eureka/
    healthcheck.enabled: true
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8081/profile/me
