spring.application.name: teste-social
server: 
  port: 8081
  servlet: 
    context-path: /teste-social

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8083/auth/realms/baeldung

